apiVersion: v1
kind: Pod
metadata:
  name: employeecrud-pod
  labels:
    app: employeecrud
spec:
  containers:
    - name: service
      image: goemployee_crud:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthcheck/
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 15
        successThreshold: 1
        timeoutSeconds: 15
      readinessProbe:
        httpGet:
          path: /healthcheck/
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3
      startupProbe:
        httpGet:
          path: /healthcheck/
          port: 8080
        failureThreshold: 30
        periodSeconds: 10
      resources:
        limits:
          cpu: "1"
          memory: 4Gi
        requests:
          cpu: 10m
          memory: 1Gi
      env:
        - name: SERVER_PORT
          value: "8080"
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: DB_HOST
          value: "localhost"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres_user"
        - name: DB_PASSWORD
          value: "userspw"
        - name: DB_NAME
          value: "users_db"
        - name: DB_DRIVER_NAME
          value: "postgres"
        - name: OAUTH_ENABLED
          value: "true"
        - name: SERVER_SSL_ENABLED
          value: "true"
        - name: SERVER_SSL_CERT_FILE_PATH
          value: "/dist/ssl/cert.pem"
        - name: SERVER_SSL_KEY_FILE_PATH
          value: "/dist/ssl/key.pem"

# kubectl apply -f k8s/pod.yaml

