apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-config
  namespace: default
data:
  # Database Configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "employee_db"
  DB_DRIVER_NAME: "postgres"

  # Server Configuration
  SERVER_PORT: "8080"
  SERVER_HOST: "0.0.0.0"
  SERVER_SSL_ENABLED: "false"

  # OAuth Configuration
  OAUTH_ENABLED: "true"

  # Auth Service URL
  AUTH_SERVICE_URL: "http://auth-service:8080"

  # Kafka Configuration
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  KAFKA_CONSUMER_ENABLED: "true"
  KAFKA_CONSUMER_GROUP_ID: "employee-group"

  # Kafka Producer Topics
  KAFKA_PRODUCER_EMPLOYEE_INSERT_TOPIC: "employee-insert.v1"
  KAFKA_PRODUCER_EMPLOYEE_UPDATE_TOPIC: "employee-update.v1"
  KAFKA_PRODUCER_EMPLOYEE_DELETE_TOPIC: "employee-deletion.v1"

  # Kafka Consumer Topics
  KAFKA_CONSUMER_EMPLOYEE_INSERT_TOPIC: "employee-insert.v1"
  KAFKA_CONSUMER_EMPLOYEE_UPDATE_TOPIC: "employee-update.v1"
  KAFKA_CONSUMER_EMPLOYEE_DELETE_TOPIC: "employee-deletion.v1"

  # Kafka DLT Topics
  KAFKA_CONSUMER_EMPLOYEE_INSERT_DLT: "employee-insert.v1.dlt"
  KAFKA_CONSUMER_EMPLOYEE_UPDATE_DLT: "employee-update.v1.dlt"
  KAFKA_CONSUMER_EMPLOYEE_DELETE_DLT: "employee-deletion.v1.dlt"
