apiVersion: v1
kind: Secret
metadata:
  name: employee-secret
  namespace: default
type: Opaque
stringData:
  DB_USER: "employee_user"
  DB_PASSWORD: "employeepw"
  OAUTH_CLIENT_SECRET: "password"
  OAUTH_USER_PASSWORD: "secret"
