volumes:
  keycloak-pg-data:
    name: keycloak-pg-data
    driver: local
  keycloak-pg-preinitdb:
    name: keycloak-pg-preinitdb
    driver: local
  keycloak-pg-initdb:
    name: keycloak-pg-initdb
    driver: local

services:
  auth-service:
    build:
      context: ../
      dockerfile: auth-service/Dockerfile
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      DB_HOST: "postgres_db"
      DB_PORT: "5432"
      DB_NAME: "auth_db"
      DB_USER: "employee_user"
      DB_PASSWORD: "employeepw"
      SERVER_PORT: "8080"
      SERVER_HOST: "0.0.0.0"
      SERVER_SSL_ENABLED: "false"
      OAUTH_ENABLED: "true"
      OAUTH_PROVIDER: "keycloak"
      KEYCLOAK_AUTH_SERVER_URL: "http://keycloak-x:8080"
      KEYCLOAK_REALM: "dev"
      OAUTH_CLIENT_ID: "client"
      OAUTH_CLIENT_SECRET: "password"
      OAUTH_USER_ID: "000000"
      OAUTH_USER_NAME: "user"
    healthcheck:
      test: curl --fail http://localhost:8080/healthcheck/ || exit 1
      interval: 5s
      retries: 15
      start_period: 20s
      timeout: 10s
    depends_on:
      - keycloak-x
      - postgres_db
  employee-service:
    build:
      context: ../
      dockerfile: employee-service/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "postgres_db"
      DB_PORT: "5432"
      DB_NAME: "employee_db"
      DB_USER: "employee_user"
      DB_DRIVER_NAME: "postgres"
      DB_PASSWORD: "employeepw"
      SERVER_PORT: "8080"
      SERVER_HOST: "0.0.0.0"
      OAUTH_ENABLED: "true"
      SERVER_SSL_ENABLED: "false"
      SERVER_SSL_CERT_FILE_PATH: "/dist/ssl/cert.pem"
      SERVER_SSL_KEY_FILE_PATH: "/dist/ssl/key.pem"
      AUTH_SERVICE_URL: "http://auth-service:8080"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      EMPLOYEE_CONSUMER_HOST: "http://employee-consumer:8080"
    healthcheck:
      test: curl --fail http://localhost:8080/healthcheck/ || exit 1
      interval: 5s
      retries: 15
      start_period: 20s
      timeout: 10s
    depends_on:
      - auth-service
      - kafka
      - employee-consumer
  employee-consumer:
    build:
      context: ../
      dockerfile: employee-consumer/Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      DB_HOST: "postgres_db"
      DB_PORT: "5432"
      DB_NAME: "employee_db"
      DB_USER: "employee_user"
      DB_DRIVER_NAME: "postgres"
      DB_PASSWORD: "employeepw"
      SERVER_PORT: "8080"
      SERVER_HOST: "0.0.0.0"
      OAUTH_ENABLED: "true"
      SERVER_SSL_ENABLED: "false"
      SERVER_SSL_CERT_FILE_PATH: "/dist/ssl/cert.pem"
      SERVER_SSL_KEY_FILE_PATH: "/dist/ssl/key.pem"
      AUTH_SERVICE_URL: "http://auth-service:8080"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    healthcheck:
      test: curl --fail http://localhost:8080/healthcheck/ || exit 1
      interval: 5s
      retries: 15
      start_period: 20s
      timeout: 10s
    depends_on:
      - auth-service
      - kafka
      - postgres_db
  keycloak-x-pg:
    container_name: ws-keycloak-x-pg
    image: docker.io/postgres:${KEYCLOAK_POSTGRES_VERSION}
    restart: unless-stopped
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U ${KEYCLOAK_POSTGRES_USER} -d ${KEYCLOAK_POSTGRES_DATABASE} || exit 1
      interval: 5s
      retries: 10
      start_period: 10s
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DATABASE}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    volumes:
      - keycloak-pg-data:/bitnami/postgresql
      - keycloak-pg-preinitdb:/docker-entrypoint-preinitdb.d
      - keycloak-pg-initdb:/docker-entrypoint-initdb.d

  keycloak-import:
    image: docker-keycloak-import
    build:
      context: .
      dockerfile: keycloak/Dockerfile.import
    restart: "no"
    environment:
      KC_DB_URL: jdbc:postgresql://ws-keycloak-x-pg:5432/${KEYCLOAK_POSTGRES_DATABASE}
      KC_DB: postgres
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    depends_on:
      keycloak-x-pg:
        condition: service_healthy

  keycloak-x:
    container_name: ws-keycloak-x
    image: docker.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    command: ["start-dev", "--verbose"]
    restart: unless-stopped
    ports:
      - "8084:8080"
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET /realms/master/ HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 && head -1 <&3 | grep -q 200"]
      interval: 5s
      retries: 30
      start_period: 30s
      timeout: 5s
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_HOSTNAME: localhost
      KC_DB_URL: jdbc:postgresql://ws-keycloak-x-pg:5432/${KEYCLOAK_POSTGRES_DATABASE}
      KC_DB: postgres
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    depends_on:
      keycloak-import:
        condition: service_completed_successfully
      keycloak-x-pg:
        condition: service_healthy
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "employee-upsert.v1:1:1,employee-insert.v1:1:1,employee-update.v1:1:1,employee-deletion.v1:1:1"
  postgres_db:
    image: postgres:latest
    restart: always
    ports:
        - "5433:5432"
    environment:
        POSTGRES_DB: employee_db
        POSTGRES_USER: employee_user
        POSTGRES_PASSWORD: employeepw

